### ISSUE TITLE
Switch-to-tab does not work since Firefox 35

### ISSUE THREAD

**Issue by Elusive138** [Elusive138/InstantFox#1]
Switch-to-tab does not seem to do anything on Firefox 35.

**Comment by Elusive138** [comment]
After enabling addon debugging:

    NS_ERROR_MALFORMED_URI: Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIIOService2.newURI] browser.js:16542

This was due to a change in FF35 (https://github.com/mozilla/gecko-dev/commit/b660c827ef578584a6d302e51dd37d3bc1e25502#diff-32ca2785c0a7d5a2a606a647e164bfe3L742), apparently related to the new search bar.

`_parseActionUrl` now returns an object with a `params` property instead of the `param` property InstantFox expects. The `params` property itself is a string containing a `url` property, which should be (in this case) functionally identical to the old `param` property.

**Comment by Elusive138** [comment]
Fixed in v2.9.11elupatch1

**Comment by GJRobert** [comment]
Thanks a lot!

**Comment by Elusive138** [comment]
@GJRobert This fix was pulled into the [official Instantfox repo](https://github.com/estivo/Instantfox) in [PR #99](https://github.com/estivo/Instantfox/pull/99), and was incorporated into release 3.0.0. This particular repo was created before I discovered the official one to fork off.
